### ISSUE TITLE
Lenke med sporing

### ISSUE THREAD

**Issue by max-nav** [navikt/decorator-next#36]
Implementer en løsning for "lenke med sporing"

**Comment by max-nav** [comment]
- [ ] Set opp test prosjekt i amplitude
- [ ] Valider at events kommer igjennom

**Comment by max-nav** [comment]
## Todo list

To forskjellige type entrypoints, logAmplitudeEvent og LenkeMedSporing. 

### logAmplitudeEvent

- [ ] Feedback
```ts
logAmplitudeEvent('tilbakemelding', { kilde: 'footer', svar: 'ja' });
```
---

- [ ] Skiplink - Denne må lages først.
```ts
logAmplitudeEvent('skiplinks', { kilde: 'header', fritekst: 'skiplinks-ga-til-hovedinnhold' });
```

---

- [ ] Varselboks  
  - Når varselboksen klikkes 
 
 ```ts 
 logAmplitudeEvent('navigere', { 
    komponent: type.toLowerCase() == "beskjed" ? "varsel-beskjed" : "varsel-oppgave", 
    kategori: "varselbjelle", 
    destinasjon: href 
});
```

---

####  AlleVarslerLenke
Lenken i bunn av varsel popup

- [ ] Done
```ts
{
	category: AnalyticsCategory.Header,
	action: 'varsler/visalle',
	label: props.tidligereVarslerUrl,
}
```

Her ser onClick slik ut:
```ts
onClick={() => logAmplitudeEvent('navigere', { komponent: 'tidligere-varsler-lenke', kategori: "varselbjelle", lenketekst: "Tidligere varsler" })}
```

---

#### SokResultater
- [ ] Done

```ts
logAmplitudeEvent('resultat-klikk', {
	destinasjon: '[redacted]',
	sokeord: '[redacted]',
	treffnr: index + 1,
});
```
---
#### Arkiver knapp
- [ ] Done

```ts
logAmplitudeEvent("arkivert-beskjed", { komponent: "varsler-beskjed-arkiverbar", kategori: "varsler" });
```
---

#### logPageView
Logger besøk og embedder dekoratør parametere, sikkerhetsnivå og dokument tittelen. Denne kjøres når brukeren laster siden.

- [ ] Done

```ts
export const logPageView = (params: Params, authState: InnloggingsstatusState) => {
    return logAmplitudeEvent('besøk', {
        sidetittel: document.title,
        innlogging: authState.data.securityLevel ?? false,
        parametre: {
            ...params,
            BREADCRUMBS: !!(params?.BREADCRUMBS && params.BREADCRUMBS.length > 0),
            ...(params.AVAILABLE_LANGUAGES && {
                AVAILABLE_LANGUAGES: params.AVAILABLE_LANGUAGES.map((lang) => lang.locale),
            }),
        },
    });
};
```
---

## analyticsEventArgs

For lenker / komponenter hvor det sendes inn til LenkeMedSporing

---

#### brodsmuleti

Specifics too verbose to include in this issue.

- [ ] Done

---

#### FooterLenker
- [ ] Done

Wrapper komponent som bruker LenkeMedSporing.

getLang util:
```ts
const localeSegments: { [locale: string]: string } = { no: 'no', en: 'en', se: 'se' };

// Workaround to get the lang attribute for links to alternative language versions of the site
const getLang = (url: string) => {
    const lastSegment = url.split('/').slice(-1)[0];

    return localeSegments[lastSegment];
};
```


```ts
analyticsEventArgs={{
	category: AnalyticsCategory.Footer,
	action: `kontakt/${lenkeNode.path}`,
	label: lenkeNode.displayName,
}}
lang={getLang(lenkeNode.path)}
```

---

#### Arbeidsflatelenke

- [ ] Done

**analyticseventargs:**
```ts
{
	context: arbeidsflate,
	category: AnalyticsCategory.Meny,
	action: 'arbeidsflate-valg',
	label: lenke.key,
}
```

#### NavLogoLenke

- [ ] Done

Komponent for NAV logoen. analyticsEventArgs varier basert på hvor den er brukt.

**header regular**:
```ts
{
	context: arbeidsflate,
	category: AnalyticsCategory.Header,
	action: 'navlogo',
}}
```


**header simple**:
```ts
{
	category: AnalyticsCategory.Header,
	action: 'navlogo-mobilmeny',
}}
```

#### hovedMenyINnholdPrivat
```ts
{
        context: MenuValue.PRIVATPERSON,
        category: AnalyticsCategory.Meny,
        action: 'arbeidsflate-valg',
    };
```


Så blir label brukt som konteksten det navigeres til
```ts
<LenkeMedSporing
	href={arbgiverLenke.url}
	analyticsEventArgs={{ ...analyticsArgs, label: MenuValue.ARBEIDSGIVER }}
	onClick={(event) => {
		onContextLink(event, arbgiverLenke);
	}}
	className={'mobilPrivatArbeidsflateLenke'}
>
	<Tekst id={arbgiverLenke.lenkeTekstId} />
</LenkeMedSporing>
```

---

#### MenyLenke
- [ ] Done

Dette er komponenten som brukes for alle lenkene som vises i kolonner på menyen.

menyGruppeNavn = Snarveier, Pensjon, osv. tittelen på lenke gruppen.
Legger til en ekstra "lenkegruppe": 'innlogget meny' hvis de er innlogget.

```ts
<LenkeMedSporing
	href={href}
	id={props.id}
	analyticsEventArgs={{
		category: AnalyticsCategory.Meny,
		action: `${menyGruppeNavn}/${lenke.displayName}`,
		label: href,
		...(lenke.isMyPageMenu && { lenkegruppe: 'innlogget meny' }),
	}}
	withChevron={true}
	withLock={displayLock}
	onClick={() => dispatch(lukkAlleDropdowns())}
>
	{lenke.displayName}
</LenkeMedSporing>
```

---

#### Minsidemenyinnhold

- [ ] Done

```ts
dittNavUrl: state.environment.MIN_SIDE_URL,

<div>
	<Heading level="2" size="medium" className={style.toppSeksjonTittel}>
		<Tekst id={'min-side'} />
	</Heading>
	<LenkeMedSporing
		href={dittNavUrl}
		id={KbNav.getKbId(nodeGroup, {
			col: 0,
			row: 0,
			sub: 0,
		})}
		analyticsEventArgs={{
			category: AnalyticsCategory.Header,
			action: 'dittnav',
			label: dittNavUrl,
			lenkegruppe: 'innlogget meny',
		}}
>
		<Tekst id={'til-dittnav-forside'} />
	</LenkeMedSporing>
</div>
```

---

#### Toppseksjon
- [ ] Done

Dette er komponenten som vises i toppen av menyen når den er åpnet. Der hvor det står "til forsiden" osv.

XP_BASE_URL kommer fra environment

```ts
{
	context: arbeidsflate,
	category: AnalyticsCategory.Meny,
	action: `hovedmeny/forsidelenke`,
	label: XP_BASE_URL,
}
```
---

## minside-knapper/MinsideArbgiverKnapp

- [ ] Done

Vises til høyre i menyen. Sjekk koden i HeaderMenyLinje.tsx som ser slik ut:
```ts
{visMinsideKnapper && (
	<div className={style.minsideKnapper} data-hj-suppress={''}>
		{innloggetPrivatperson && <VarslerKnapp kbNavMainState={kbNavMainState} />}
		{innloggetPrivatperson && <DesktopMinsidemenyKnapp kbNavMainState={kbNavMainState} />}
		{innloggetArbeidsgiver && <MinsideArbgiverKnapp />}
		{innloggingsstatus === Status.OK && <LoggInnKnapp />}
	</div>
)}
{!visMinsideKnapper && <LoggInnKnapp />}
```

```ts
analyticsEventArgs={{
	category: AnalyticsCategory.Header,
	action: 'minside-arbeidsgiver',
	label: href,
}}
```
---

#### innlogget/MobilInnloggetForsideLenke
- [ ] Done

Komponent for "Til forside" som kalkulerer riktig analyticsEventArgs basert på props. 

dette er hvordan lenkeprops kalkuleres.
export const valgtbedrift = () => {
    const orgnummerFraUrl = new URLSearchParams(window.location.search).get('bedrift');
    return orgnummerFraUrl ? `?bedrift=${orgnummerFraUrl}` : '';
};


const lenkeProps =
	arbeidsflate === MenuValue.PRIVATPERSON
		? {
			  tekstIdHeader: 'min-side' as const,
			  tekstIdLenke: 'til-dittnav-forside' as const,
			  href: MIN_SIDE_URL,
			  analyticsAction: 'dittnav',
		  }
		: arbeidsflate === MenuValue.ARBEIDSGIVER
		? {
			  tekstIdHeader: 'min-side-arbeidsgiver' as const,
			  tekstIdLenke: 'ga-til-min-side-arbeidsgiver' as const,
			  href: MINSIDE_ARBEIDSGIVER_URL + valgtbedrift(),
			  analyticsAction: 'minside-arbeidsgiver',
		  }
		: null;

```

```ts
analyticsEventArgs={{
	category: AnalyticsCategory.Header,
	action: lenkeProps.analyticsAction,
	label: lenkeProps.href,
	lenkegruppe: 'innlogget meny',
}}

**Comment by max-nav** [comment]
Setter denne litt på pause til etter møte med Tobias. Starter med en kortere liste. 

- [ ] Feedback
```ts
logAmplitudeEvent('tilbakemelding', { kilde: 'footer', svar: 'ja' });
```
---
- [ ] Varselboks  
  - Når varselboksen klikkes 
 
 ```ts 
 logAmplitudeEvent('navigere', { 
    komponent: type.toLowerCase() == "beskjed" ? "varsel-beskjed" : "varsel-oppgave", 
    kategori: "varselbjelle", 
    destinasjon: href 
});
```
---
#### SokResultater
- [ ] Done

```ts
logAmplitudeEvent('resultat-klikk', {
	destinasjon: '[redacted]',
	sokeord: '[redacted]',
	treffnr: index + 1,
});
```

---

#### Arkiver knapp
- [ ] Done

```ts
logAmplitudeEvent("arkivert-beskjed", { komponent: "varsler-beskjed-arkiverbar", kategori: "varsler" });
```
---
